type = "about"
title = "About"

[profile]
research_interests = [
  "Platform and Digital Publics",
  "Digital Gender Politics",
  "Mixed Methods",
  "To be continued..."
]

[[sections]]
id = "about"
type = "markdown"
source = "bio.md"
title = "About"

[[sections]]
id = "education"
type = "education"
title = "Education"
source = "education.toml"
