[site]
title = "Zhihong Li Academic Homepage"
description = "Master Student at the University of Oxford."
favicon = "/favicon-bacon.svg"
last_updated = "July 19, 2026"

[author]
name = "Zhihong Li"
title = "Master Student"
institution = "The University of Oxford"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "zhihong.li@sociology.ox.ac.uk"
google_scholar = "https://scholar.google.com/citations?user=6aQoZGUAAAAJ&hl=en"
orcid = "https://orcid.org/0009-0003-2179-9325"

[features]
# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Research"
type = "page"
target = "publications"
href = "/publications/"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services/"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv/"
